const Bg_img=new Image();
Bg_img.src="img/bg.png";
const score_img=new Image();
score_img.src="img/coins.png";
const life_img=new Image();
life_img.src="img/life.png"
const life_img2=new Image();
life_img2.src="img/life2.png"
const level_img=new Image();
level_img.src="img/level2.png"
const ball_hit=new Audio();
ball_hit.src="sound/paddle_hit.mp3"
const wall_hit=new Audio();
wall_hit.src="sound/bat_hit_ball.mp3"
const level_up_sound=new Audio();
level_up_sound.src="sound/level_up_sound.mp3";
const life_lost=new Audio();
life_lost.src="sound/life_lost.mp3"
const win=new Audio();
win.src="sound/win.mp3";